name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: |  
        docker build . --tag juice-shop
        docker container run -d -p 3000:3000 juice-shop
    - name: Wait 10 secs
      run: sleep 10
    - name: Call to localhost
      run: curl http://localhost:3000
