name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build --tag Dockerfile
    - name: Run with docker Container
      run: docker container run -d -p 3000:3000 juice-shop
    - name: Call to localhost
      run: curl http://localhost:3000
